[package]
name = "mychat"
version = "0.1.0"
authors = ["jglrxavpok <jglrxavpok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
ansi_term = "0.12.1"